# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='description',
        ),
    ]
