# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_remove_album_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.CharField(default='相册描述', max_length=300),
        ),
    ]
