# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-02 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(default='aaaa@gmail.com', max_length=254, unique=True)),
                ('sex', models.BooleanField(default=True)),
                ('age', models.IntegerField(default=10)),
                ('img', models.ImageField(default='default/default.jpg', upload_to='photo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
    ]
